version: "2"

services:
  vucar-service-dev:
    build:
      context: ./src
      dockerfile: ./Dockerfile
      target: development
    image: vucar-app-server-image-dev
    container_name: vucar-app-server-container-dev
    profiles:
      - dev
    ports:
      - 8001:8001
    # environment:
    #   - PORT=${PORT}
    env_file:
      - ./.env
    depends_on:
      - postgres-db
    links:
      - postgres-db
    volumes:
      - ./src/app:/app
      - ./src/logs:/var/logs
      - ./static:/static

  postgres-db:
    container_name: postgres-db
    image: postgres
    profiles:
      - prod
      - dev
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - ./.env

volumes:
  postgres_db: